name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: doc-modelagem_banco_dados

    steps:
      - name: Checagem do código
        uses: actions/checkout@v3

      - name: Configurando o Noje.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando dependências
        run: npm install

      - name: Build do site com documentação 🚀
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc-modelagem_banco_dados/build

    #   - name: Upload artifact
    #     uses: actions/upload-pages-artifact@v2
    #     with:
    #       # 👇 Specify build output path
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: main
    #       path: ./doc-modelagem_banco_dados/build
    #       name: page
    #       if-no-files-found: error

    #   - name: Deploy to GitHub Pages
    #     id: deployment
    #     uses: actions/deploy-pages@v2
